### ISSUE TITLE
Class name does not fit java conventions

### ISSUE THREAD

**Issue by maximilize** [austinksmith/react-native-hamsters#2]
In java world, class names normally start with a capital letter, and variables which also might hold instances of a class start with a lowercase one.

Why not rename `reactNativeHamstersModule` to `ReactNativeHamstersModule`, the same for the package class?

**Comment by austinksmith** [comment]
Thank you for creating this issue, if you want to submit a pr I'd be happy to review it. Right now the library is functional and I don't want to make any unnecessary changes. I like your suggestion I just don't have the bandwidth at the moment to I tackle this.

**Comment by austinksmith** [comment]
@maximilize I am in the process of fixing this today

**Comment by austinksmith** [comment]
@maximilize this is now resolved with https://github.com/austinksmith/react-native-hamsters/pull/4
