### ISSUE TITLE
Move to JSI (C++ for both Android and IOS)

### ISSUE THREAD

**Issue by gomes042** [austinksmith/react-native-hamsters#3]
Example of library using `std::thread`

[react-native-multithreading](https://www.npmjs.com/package/react-native-multithreading)

**Comment by runtothedoor** [comment]
@austinksmith Do you know if that would bring more performance or another benefit?

**Comment by austinksmith** [comment]
Thanks for creating this issue/suggestion. My c++ skills are lacking to say the least. I did look at the library you linked and it seems interesting though it doesn't follow the Web worker API standard which is something I strive for with hamsters.js. If you want to create a PR id be happy to review it, thank you

**Comment by austinksmith** [comment]
@lgxm3z I am going to attempt to implement this with JSI but it will likely be a new repo so I can maintain this one for 0.69 support and older, the new JSI implementation I will be targeting new releases of react native, what version are you running?

**Comment by gomes042** [comment]
> @lgxm3z I am going to attempt to implement this with JSI but it will likely be a new repo so I can maintain this one for 0.69 support and older, the new JSI implementation I will be targeting new releases of react native, what version are you running?

I don't use RN anymore, but thanks and good luck! : )
